### ISSUE TITLE
About the characteristics of the dataset.

### ISSUE THREAD

**Issue by baipianpian** [Phylliida/British-National-Corpus-Spoken-Subset#2]
Is Twiiter's dataset made by yourself, or is it someone else to create? What are the characteristics of this data set, what areas (such as specific areas or commonsense areas), and what topics?
（I used this for the first time, I am not very familiar with it. I hope I am not using it wrong.
）

**Comment by Phylliida** [comment]
I scraped the Twitter dataset myself, what I did is that you can see if a tweet replied to someone else, so I just scraped the general feed and looked to see if the tweet was a reply. If it was, I walked up the chain and scraped each tweet. If the chain was long enough (3 or more, if I remember correctly), I appended it to my dataset.

Topics are whatever people are talking about that day, nothing specific. Feel free to use it however you want :)
